### ISSUE TITLE
Custom resolution don`t work.

### ISSUE THREAD

**Issue by Dan7s** [truckersmp-cli/truckersmp-cli#79] opened 2020-06-05 14:47 UTC
I tried to run truckersmp-cli with custom resolution, setted in
~/.local/truckersmp-vli/Euro Truck Simulator 2/steamuser/My Documents/Euro Truck Simulator 2/config.cfg

and resolution part of config.cfg looks like this:
`uset r_fullscreen "0"`
`uset r_mode_refresh "0"`
`uset r_mode_height "1080"`
`uset r_mode_width "4480"`

On classic steam version, without truckersmp-cli, it works perfectly as it shoud.

**Comment by Lucki** [comment] 2020-06-05 15:05
Great, you ignored the template. From the information you gave us I can tell your path is wrong. Try edit this file instead:
~~~
"$XDG_DATA_HOME/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/users/steamuser/My Documents/Euro Truck Simulator 2/config.cfg"
~~~

**Comment by Lucki** [comment] 2020-06-05 16:39
> What additional information I should provide?

As much as possible.
The most important part seems to be the game log because it contains the config file path and the read options. `$XDG_DATA_HOME/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/users/steamuser/My Documents/game.log.txt`

**Comment by Dan7s** [comment] 2020-06-05 17:08
[game.log.txt](https://github.com/lhark/truckersmp-cli/files/4737504/game.log.txt)

`Arch Linux`
`Kernel: 5.6.15-arch1-1`
`DE: Xfce`

**Comment by Lucki** [comment] 2020-06-06 16:13
> On classic steam version, without truckersmp-cli, it works perfectly as it shoud.

Native or with Proton?

The game reads the correct config file:
~~~
00:00:01.329 : [ufs] Home directory: 'C:/users/steamuser/My Documents/Euro Truck Simulator 2'.
00:00:01.580 : exec /home/config.cfg
00:00:01.580 : [sys] Executing /home/config.cfg ...
~~~

And also reads your options:
~~~
00:00:01.591 : uset r_fullscreen "0"
00:00:01.591 : uset r_mode_refresh "0"
00:00:01.591 : uset r_mode_height "1080"
00:00:01.591 : uset r_mode_width "4480"
~~~

You could try DXVK or wined3d to see if it's working through DX11/Vulkan instead of OpenGL.

**Comment by Dan7s** [comment] 2020-06-11 17:16
> Native or with Proton?
Native.

> You could try DXVK or wined3d to see if it's working through DX11/Vulkan instead of OpenGL.
wined3d also does not work

**Comment by Lucki** [comment] 2020-06-12 18:01
I've tested here and the fullscreen option get's picked up so the options generally work.
My guess that the custom resolution doesn't work is related to the proton/wine part (or maybe truckersmp) and isn't caused by this script.
Some things you could try:
* Check if the custom resolutions generally work with Proton by forcing the use of Proton in steam and setting your options there
* Check if the options work in use with plain wine instead of proton
* Try altering with the custom desktop resolution settings in winecfg

**Comment by Lucki** [comment] 2021-11-26 13:45
There's also `--wine-desktop SIZE` now to play around with.

Closing because this is probably something we can't fix as the options are correctly getting picked up by the game.

**Closed by Lucki** 2021-11-26 13:45 UTC
