### ISSUE TITLE
DLC loads but isn't installed. (Solved, fix instructions inside)

### ISSUE THREAD

**Issue by XylonWasTaken** [truckersmp-cli/truckersmp-cli#253] opened 2021-11-23 04:49 UTC
So basically I have the Heavy Cargo DLC, and had noticed it doesn't show up in the DLC manager as installed or downloaded, I checked the data directory and I have all the DLC's inside the folder, checked the logs and it says it has been validated or loaded by the game.

FIX - 
Now on how I fixed it is that I downloaded and installed the native version of ETS2 through Linux Steam, and then ran the command `truckersmp-cli start ets2` and checked that it has loaded and installed the DLC that I want. The reason for how the error came to be is that I uninstalled the game to save space for games and documents. (I'm assuming other DLC's like map, paint, etc, works this way)

Adding a note in the `README.md` that you have the native version of ETS2 for DLC's to work will be helpful for other people

**Comment by Lucki** [comment] 2021-11-23 13:36
> On Linux it's possible to start TruckersMP through Proton. A working native Steam installation is needed for this **which has the desired game installed or with an update pending**. SteamCMD can use your saved credentials for convenience.

It's already mentioned in the third(!) paragraph. But I admit we should also put this into the known issues section.

**Comment by Lucki** [comment] 2021-11-23 13:37
Duplicate of #129

**Closed** 2021-11-23 23:05 UTC

**Comment by femrek** [comment] 2022-07-31 19:34
This problem occurred on me because steam doesn't add the drive which ets 2 is installed on start up automatically. I added the drive and it has solved. for add drive open Steam > Settings > Downloads > Steam Library Folders then add missing drive.

![Screenshot from 2022-07-31 22-22-22](https://user-images.githubusercontent.com/29581978/182041919-cf74d190-a1a7-4274-b0bc-f8fdfdc8e58b.png)

**Comment by puyoxyz** [comment] 2022-08-09 10:50
> This problem occurred on me because steam doesn't add the drive which ets 2 is installed on start up automatically. I added the drive and it has solved. for add drive open Steam > Settings > Downloads > Steam Library Folders then add missing drive.
> 
> ![Screenshot from 2022-07-31 22-22-22](https://user-images.githubusercontent.com/29581978/182041919-cf74d190-a1a7-4274-b0bc-f8fdfdc8e58b.png)

Same issue here. It seems that every time I `truckersmp-cli update` or `truckersmp-cli ustart`, it gets rid (not deletes but just makes steam not detect) my library folders other than the default one. Annoying :(

**Comment by Lucki** [comment] 2022-08-09 11:07
Please compare your `$XDG_DATA_HOME/Steam/steamapps/libraryfolders.vdf` before and after that happens.
If there's something that changes we could back up and rewrite the file.
